# Image officielle légère
FROM postgres:16-alpine

# Copier scripts d'initialisation
COPY ./db /docker-entrypoint-initdb.d/

COPY ./postgresql.conf /etc/postgresql/postgresql.conf


EXPOSE 5432

# Santé du conteneur via pg_isready
HEALTHCHECK --interval=10s --timeout=5s --retries=5 \
  CMD pg_isready -U ${POSTGRES_USER} || exit 1

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]