max_connections = 100
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB
effective_cache_size = 256MB

# Logs
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql.log'
log_statement = 'all'